import type { Metadata } from "next";
import "../../globals.css";
import Nav from "@/app/components/nav";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav/>
      {children}
    </>
  );
}
